### ISSUE TITLE
Image Flipped 

### ISSUE THREAD

**Issue by zaherhadiar** [aws-amplify/amplify-ui-swift-liveness#103]
Dear,
I as using liveness 1.2.2, when i finish face liveness the image is flipped.
Before updating to this version it was working fine

**Comment by phantumcode** [comment]
@zaherhadiar Thanks for submitting the issue.  Can you provide additional details to help with the investigation?  What are the steps to reproduce the issue? Is this a native iOS app or flutter/reactnative app?  Is the image you're referring to from the GetLivenessResult audit image data?

**Comment by phantumcode** [comment]
This issue is fixed in [v1.2.4](https://github.com/aws-amplify/amplify-ui-swift-liveness/releases/tag/1.2.4)

**Comment by zaherhadiar** [comment]
Thanks, will check if issue is fixed.

**Comment by zaherhadiar** [comment]
Issue is fixed thanks
