### ISSUE TITLE
support cocopods

### ISSUE THREAD

**Issue by LiangLuDev** [aws-amplify/amplify-ui-swift-liveness#110]
### Is your feature request related to a problem? Please describe.

Cannot be imported using cocopods

### Describe the solution you'd like

Cannot be imported using cocopods

### Describe alternatives you've considered

Cannot be imported using cocopods

**Comment by phantumcode** [comment]
@LiangLuDev Thanks for submitting your feature request.  We currently don't have any plans to support cocoapods.  Is there any particular reason you can integrate the Liveness component using SPM?

**Comment by LiangLuDev** [comment]
> @LiangLuDev Thanks for submitting your feature request. We currently don't have any plans to support cocoapods. Is there any particular reason you can integrate the Liveness component using SPM?

I need to include a library in the xxx.podspec file of an iOS project within a Flutter plugin, but I'm not sure how to do it using other methods. If there is a better way, please recommend. Thank you.

**Comment by phantumcode** [comment]
@LiangLuDev Have you tried including the component via Swift Package Manager?

**Comment by LiangLuDev** [comment]
> @LiangLuDev Have you tried including the component via Swift Package Manager?

Hello, I used to do Android development, I don't know much about iOS, I looked up some information, and tried to use smp in pods, I don't know if my operation is wrong? Is there any documentation I can refer to

**Comment by MRJYL** [comment]
If your project does not support SPM, you can try building a dynamic library and use it, I am using it in my project. @LiangLuDev

**Comment by LiangLuDev** [comment]
> If your project does not support SPM, you can try building a dynamic library and use it, I am using it in my project. @LiangLuDev

兄弟你好，我想问一下动态库是什么形式的？你有现成的吗  可以加你联系方式吗

**Comment by phantumcode** [comment]
@LiangLuDev Here's a tutorial on how to use Swift Package Manager: https://www.kodeco.com/7242045-swift-package-manager-for-ios

**Comment by LiangLuDev** [comment]
> @LiangLuDev Here's a tutorial on how to use Swift Package Manager: https://www.kodeco.com/7242045-swift-package-manager-for-ios

Hello, I need to turn this liveness function into a Flutter plugin, so I don't know how to use this function in the podspec file, or is there any way to use SPM in the Pod project. I don't want to use the liveness function in the main project.

**Comment by phantumcode** [comment]
Currently, you can integrate Swift Liveness component via platform channels in the main project https://docs.flutter.dev/platform-integration/platform-channels.   We currently don't have any plans to add cocoapod support.
