### ISSUE TITLE
Feature request: Improve error messages

### ISSUE THREAD

**Issue by alekkova** [aws-amplify/amplify-ui-swift-liveness#114]
### Is your feature request related to a problem? Please describe.

There are only a handful of error cases defined for face liveness session without any additional description. One of those errors is also an `unknown` error. Such limited error reporting makes it hard to understand issues that users are facing.

An example of receiving an `unknown` error was also reported here: https://github.com/aws-amplify/amplify-swift/issues/3546

### Describe the solution you'd like

Provide better error descriptions. Avoid using an `unknown` error or attach the underlying error description to the error case.

### Describe alternatives you've considered

There are no alternatives.

**Comment by mRamzii** [comment]
+1

My implementation also returns unknown errors a lot of the times, I can't figure out what the problem is... This feature would be very appreciated
