### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by zaherhadiar** [aws-amplify/amplify-ui-swift-liveness#120]
### Describe the bug

Sometimes the liveness challenges is not working fine it is giving blank page, this occurs when I change the ISP connection.I need to know the reason behind that or what are the apis that are called from ur side in the SDK

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

Chaning ISP Network

### Swift Liveness Version

no specific version

### Xcode version

no specific version

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### OS Version

no specific version

### Device

no specific version

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by phantumcode** [comment]
@zaherhadiar Thanks for submitting the issue.  Can you additional details to help us troubleshoot the issue?
1. What version of liveness are you using?
2. What are the exact steps to reproduce the issue? Can you clarify what "change ISP network" mean? Are you changing the connected wifi network before, after, or during a liveness check?

**Comment by phantumcode** [comment]
This issue will close soon due to inactivity.
