### ISSUE TITLE
Do we support Cocopod?

### ISSUE THREAD

**Issue by pmd30011991** [aws-amplify/amplify-ui-swift-liveness#164]
### Is your feature request related to a problem? Please describe.

Currently our project is using CocoaPod to manage dependencies. is it anyway we can build the deb file from source on github?

### Describe the solution you'd like

Be able to build Cocoapod deb file

### Describe alternatives you've considered

Any wait or commant to run the build manually

**Comment by ruisebas** [comment]
Hi @pmd30011991. We currently don't have any plans to support CocoaPods.
You might be able to consume this package through SPM and keep the rest of your dependencies on CocoaPods, provided there's no naming conflicts.
