### ISSUE TITLE
Error "No plugins added to Authentication category."

### ISSUE THREAD

**Issue by behzod-rajabov** [aws-amplify/amplify-ui-swift-liveness#183]
### Describe the bug

I created Amplify with ClientID and clientSecret, and added auth category to it. And I added the generated amplifyconfiguration.json file to the Project. And I configured Amplify in AppDelegate as follows:

```
Amplify.Logging.logLevel = .debug
        do {
            try Amplify.add(plugin: AWSPredictionsPlugin())
            try Amplify.configure()
            print("Amplify successfully configured")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }
```
But I am getting the following error:
![image](https://github.com/user-attachments/assets/9f3761e7-351b-45ef-84e1-f0e8a986b28f)

### Steps To Reproduce

```swift
===
```

### Expected behavior

===

### Swift Liveness Version

1.3.3

### Xcode version

16.1 (16B40)

### Is this a regression?

Yes

### OS Version

iOS 18.1

### Device

iPhone 16 Pro Max

**Comment by vincetran** [comment]
Hi @behzod-rajabov, Looking at the code snippet you provided, it looks like you added the Predictions plugin but not the Auth plugin:

```
Amplify.Logging.logLevel = .debug
        do {
            try Amplify.add(plugin: AWSPredictionsPlugin())
            try Amplify.add(plugin: AWSCognitoAuthPlugin()) // You need to add this here
            try Amplify.configure()
            print("Amplify successfully configured")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }
```

**Comment by behzod-rajabov** [comment]
Hi @vincetran. Yes you are right. I forgot to add the Auth plugin as you said. Thanks for your help.
