### ISSUE TITLE
Why Cocoa Pods not support? 

### ISSUE THREAD

**Issue by francisco-sanabria-itti** [aws-amplify/amplify-ui-swift-liveness#187]
### Is your feature request related to a problem? Please describe.

I want to use that SMP in a Flutter library, but its not posible because SMP not compatible with Cocoapods.

### Describe the solution you'd like

I want a tool for flutter or make this library compatible with cocoapods

### Describe alternatives you've considered

make a new version for cocoapods.

**Comment by ruisebas** [comment]
Hi @francisco-sanabria-itti! We currently have no plans to support CocoaPods. 

You can add native components to a Flutter app by doing the following:
- https://docs.flutter.dev/platform-integration/ios/platform-views
- https://docs.flutter.dev/platform-integration/platform-channels

Here's an example by another customer: https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/85#issuecomment-2469818435

Thanks!
