### ISSUE TITLE
FaceLivenessDetectorView is not showing up on screen

### ISSUE THREAD

**Issue by Sandiverse** [aws-amplify/amplify-ui-swift-liveness#28]
I am developing a Flutter App and since Amplify UI Face Liveness component is not Flutter ready yet, I am showing a native screen via platform channels, but the Swift UI view is not showing once the screen is opened.

This is my Swift UI view

```
import FaceLiveness
import SwiftUI

struct FaceLivenessDetectionView: View {
    var sessionId: String?
    var awsCredentials: CustomAWSCredentials?

    var body: some View {
        if let livenessSessionId = sessionId,
           let accessKeyId = awsCredentials?.accessKeyId,
           let secretAccessKey = awsCredentials?.secretAccessKey,
           let sessionToken = awsCredentials?.sessionToken,
           let expiration = awsCredentials?.expiration
           {
            FaceLivenessDetectorView(
                sessionID: livenessSessionId,
                credentialsProvider: FlutterAWSCredentialsProvider {
                    FlutterAWSCredentials(sessionToken: sessionToken,
                                          expiration: expiration,
                                          accessKeyId: accessKeyId,
                                          secretAccessKey: secretAccessKey)
                },
                region: "us-east-1",
                isPresented: .constant(true),
                onCompletion: { result in
                    switch result {
                    case .success:
                        print("Success")
                    case .failure(let error):
                        print("Error: \(error)")
                    default:
                        print("Default")
                    }
                }
            )
        } else {
            Text("Empty View")
                .font(.largeTitle)
                .foregroundColor(.white)
                .background(Color.blue)
                .edgesIgnoringSafeArea(.all)
        }
    }
```

I am sending all the credentials needed for the component from the Flutter side and by using a custom credentials provider

This is my custom credentials provider

```
import Amplify
import AWSPluginsCore

struct FlutterAWSCredentialsProvider: AWSCredentialsProvider {
    let credentials: () -> AWSCredentials

    func fetchAWSCredentials() async throws -> AWSCredentials {
        credentials()
    }
}

struct FlutterAWSCredentials: AWSTemporaryCredentials {
    var sessionToken: String
    var expiration: Date
    var accessKeyId: String
    var secretAccessKey: String
}
```

This is how I am displaying the Swift UI view on the screen (commented lines are another way I was trying without success)

```
navigationChannel.setMethodCallHandler {
            (call: FlutterMethodCall, result: FlutterResult) in
            switch call.method {
            case "startLivenesDetection":
                guard let rootViewController = UIApplication.shared.keyWindow?.rootViewController else {
                    result(FlutterError(code: "NOT_FOUND", message: "Root view controller not found", details: nil))
                    return
                }
                guard let sessionId = self.faceLivenessSessionId else {
                    result(FlutterError(code: "NOT_FOUND", message: "Face Liveness session ID is null", details: nil))
                    return
                }
                guard let awsCredentials = self.customAWSCredentials else {
                    result(FlutterError(code: "NOT_FOUND", message: "AWS Credentials are null", details: nil))
                    return
                }
                let faceLivenessController = UIHostingController(rootView: FaceLivenessDetectionView(sessionId: sessionId,
                                                                                                     awsCredentials: awsCredentials))
//                rootViewController.present(faceLivenessController,
//                                           animated: true,
//                                           completion: nil)
                if let window = UIApplication.shared.windows.first {
                    window.rootViewController = faceLivenessController
                    window.makeKeyAndVisible()
                }
            default:
                result(FlutterMethodNotImplemented)
            }
        }
```

This implementation is working Fine on Android but not on iOS

All I see in the debug console is this

```
3 Error: Transpose unit is not supported.
2023-05-10T11:47:20-0600 info CognitoIdentityClient : [Logging] Request: POST https:443
 Path: /
 x-amz-user-agent: aws-sdk-swift/1.0,
X-Amz-Target: AWSCognitoIdentityService.GetId,
Content-Length: 79,
Content-Type: application/x-amz-json-1.1,
User-Agent: aws-sdk-swift/1.0 api/cognito-identity/1.0 os/iOS/16.4.1 lang/swift/5.8 lib/amplify-swift/2.10.0,
Host: cognito-identity.us-east-1.amazonaws.com
 Optional([])
2023-05-10T11:47:20-0600 info SerialExecutor : [Logging] Creating connection pool for Optional("https://cognito-identity.us-east-1.amazonaws.com/?")with max connections: 50
2023-05-10T11:47:20-0600 info CRTClientEngine : [Logging] Connection was acquired to: Optional("https://cognito-identity.us-east-1.amazonaws.com/?")
```

Let me know if there is something else I can try or provide in order to help this issue being solved.

**Comment by devedup** [comment]
I'm using a pure SwiftUI context and experiencing the same white screen.

**Comment by atierian** [comment]
> I'm using a pure SwiftUI context and experiencing the same white screen.

I saw that in the issue you opened. We need a bit more information to investigate this though. Can you please provide the info requested over in the issue you opened? 
- https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/30

If these end up being related, we'll consolidate the issues. But until then it's best to keep them separate to make sure we can debug this properly. Thanks!

**Comment by atierian** [comment]
If you're not using Amplify in your project already, or don't want to add it to handle auth, you don't need to use Amplify CLI to create (or update) any backend resources. 

If you're injecting a credentials provider, Amplify Auth isn't used at all.

To be clear:
1. Using Amplify Auth -> You shouldn't inject credentials provider. This is handled automatically.
2. Not using Amplify Auth -> You're responsible for credentials management and have to inject a credentials provider.

**Comment by atierian** [comment]
If you're not using Amplify Auth, you'll still need to provide valid AWS credentials to the component through the credentials provider. However they don't need to be sourced from Amazon Cognito.

**Comment by devedup** [comment]
Thanks. Yes, currently I have an AWS IAM user with this inline policy

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "rekognition:StartFaceLivenessSession",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "rekognition:CreateFaceLivenessSession",
            "Resource": "*"
        }
    ]
}
```

… but it still would mean embedding the key/secret in my code - or returning them from a backend call after auth….. which still exposes them. 

The use case is that I have users that are already authenticated on a dating app, and they can opt in to have their profile/account photos verified. I’m already using Recognition to detect faces match successfully, but need to add another layer to stop fake photos getting through. Hence using Face Liveness to detect real people.

**Comment by Sandiverse** [comment]
Thank you for reply @atierian.

I have tested this component in a pure Swift UI context application as you suggested it and the component is working as expected. So maybe it is something related to Flutter Platform channels.

I was even trying with Flutter Platform Views and the screen opens black but now the green dot in the status bar appears like if the camera is doing something but nothing shows up.

In the end I can not tell if the problem is completely from Flutter or if it is a combination of some sort of implementation in the Amplify library for the Face Liveness Swift UI component and Flutter.

**Comment by Sandiverse** [comment]
Hi, it's been a while, I hope you're doing well.

Unfortunalety, I'm still not able to make it work.

I made a github repo with a sample project for you to test, I hope it helps.

https://github.com/Sandiverse/flutter_swift_face_liveness

I added to the readme some guidance in order to configure the project.

**Comment by atierian** [comment]
Thanks for the sample project link. I'll follow up here with any updates.

**Comment by Sandiverse** [comment]
Hello, it's been a long time, sorry for the insistence but I would like to know if there is any update on this.

**Comment by atierian** [comment]
No updates yet. If you discover that there's a Flutter compatibility issue and have a root cause, please let us know and we'll see if we can address it.

Thanks for your patience.

**Comment by Sandiverse** [comment]
Hi there,

I'm glad to tell that after upgrading Amplify UI Swift package to version 1.1.0 the bug seems to have dissapeared.

Now I have a completely successful hybrid implementation of this component between Flutter and Native Swift iOS.

Thank you @atierian for all your help.

**Comment by atierian** [comment]
That's great to hear 🎉 
Thanks for letting us know!

**Comment by user2634** [comment]
Hi there does someone have any advices for this issue pls help?  
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/52
