### ISSUE TITLE
Documentation for detecting face liveness

### ISSUE THREAD

**Issue by junjielu** [aws-amplify/amplify-ui-swift-liveness#29]
I looked through the online documentation, but found no guidelines related to face liveness detection. I was wondering if there are plans to add face detection related usage and examples?

**Comment by atierian** [comment]
Thanks for opening this issue @junjielu.

You can find documentation for FaceLiveness [here](https://ui.docs.amplify.aws/swift/connected-components/liveness).
We also have an example application [here](https://github.com/aws-amplify/amplify-ui-swift-liveness/tree/main/HostApp) with instructions on how to set up your Amplify backend. 

Let me know if you have any other questions. Thanks!

**Comment by junjielu** [comment]
Oh, I saw that. I noticed that this repo is based on SwiftUI and I was wondering if it introduces the use of the UIKit app?

**Comment by atierian** [comment]
The FaceLivessDetector UI component only exposes SwiftUI APIs, so we don't have full examples of using it from UIKit.

You can use [UIHostingController](https://developer.apple.com/documentation/swiftui/uihostingcontroller) to bring it into your UIKit view hierarchy.
