### ISSUE TITLE
Crashing while start recording for face liveness

### ISSUE THREAD

**Issue by vishal-jadav** [aws-amplify/amplify-ui-swift-liveness#35]
we are using unauth role based face liveness for our project. when it reaches to recording screen its crashing every time with following error : Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriter startWriting] Cannot call method when status is 1'

please look into this issue as earliest as possible.

**Comment by atierian** [comment]
Thanks for opening this issue @vishal-jadav. We'll investigate and follow up here with any updates.

**Comment by phantumcode** [comment]
@vishal-jadav Can you confirm if you're using the latest version 1.0.1 and if you're going to the recording screen within the session time out period?

**Comment by vishal-jadav** [comment]
@phantumcode yes i am using latest version using spm. i have implemented unauth role based login and implemented face liveness with this demo as soon as it detected face and goes to recording screen its crashing with error : -[AVAssetWriter startWriting] Cannot call method when status is 1'.

**Comment by atierian** [comment]
Resolved in release [v1.0.2](https://github.com/aws-amplify/amplify-ui-swift-liveness/releases/tag/1.0.2). 
Thanks for reporting this!
