### ISSUE TITLE
Lack of customization

### ISSUE THREAD

**Issue by ntnmrndn** [aws-amplify/amplify-ui-swift-liveness#43]
Hello,
We are thinking about implementing the liveness recognition service in our app, but the design of the UI components offer very few customization points.
We would like to know if you would be ok with us submitting a PR with either:
- More public classes, essentially allowing us to rewrite our own FaceLivenessDetectorView
or if this is too much:
- Adding customization points (state aware overlays, oval color, ...)

**Comment by atierian** [comment]
Thanks for opening this @ntnmrndn. We'll take this on as a feature request.

>  We would like to know if you would be ok with us submitting a PR with either

We welcome community contributions. Something to keep in mind; any API changes need to be carefully planned. To make sure your contributions can be merged in, I'd recommend adding a detailed overview of what you'd like to add / change. That way we can discuss the proposed changes in detail. We can use this issue for that discussion.
