### ISSUE TITLE
Error when recognize face

### ISSUE THREAD

**Issue by chinhnd** [aws-amplify/amplify-ui-swift-liveness#47]
Hello,

I checkout newest source and run, it shows the error below:

App crashed:
[AVAssetWriter startWriting] Cannot call method when status is 1

It comes from this function:

    func start() {
        guard state == .pending else { return }
        state = .writing
        assetWriter.startWriting()
        assetWriter.startSession(atSourceTime: .zero)
    }

Thank you.

**Comment by phantumcode** [comment]
@chinhnd Can you verify if your backend is configured correctly? how are you create a new session?

**Comment by phantumcode** [comment]
Closing due to lack of inactivity, please re-open if this is still an active issue.
