### ISSUE TITLE
[iOS]FaceLivenessDetectorView is shown but not like in the example the frame for face capturing is missing.

### ISSUE THREAD

**Issue by user2634** [aws-amplify/amplify-ui-swift-liveness#52]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

iOS

### Which UI component?

Liveness

### How is your app built?

swiftUI, UIKit 

### Which region are you seeing the problem in?

eu-west-1

### Please describe your bug.

FaceLivenessDetectorView is shown but not like in the example the frame for face capturing is missing.

### What's the expected behaviour?

FaceLivenessDetectorView is shown with all necessary elements

### Help us reproduce the bug!

   Just create a FaceLivenessDetectorView with customCredentialsProvider here is the example 

```swift
    private func configureFaceLivenessDetection() {
        let accessKey = "My access key"
        let secretKey = "my secret key"
        
        let customCredentialsProvider = PbCredentialsProvider(
            accessKey: accessKey,
            secretKey: secretKey,
            sessionKey: nil
        )
        if let sessionID = self.sessionID {
            let faceLivenessSwiftUIView = FaceLivenessDetectorView(
                sessionID: sessionID,
                credentialsProvider: customCredentialsProvider,
                region: "eu-west-1",
                disableStartView: false, // Your configuration
                isPresented: .constant(true),
                onCompletion: { result in
                    switch result {
                    case .success:
                        print("Liveness successfully completed")
                    case .failure(let error):
                        print("Liveness error: \(error)")
                    }
                }
            )
            
            let hostingController = createHostingController(with: faceLivenessSwiftUIView)
            addHostingControllerAsChild(hostingController)
            configureConstraints(for: hostingController.view)
        }
    }
``` 

### Code Snippet

```swift
    private func configureFaceLivenessDetection() {
        let accessKey = "My access key"
        let secretKey = "my secret key"
        
        let customCredentialsProvider = PbCredentialsProvider(
            accessKey: accessKey,
            secretKey: secretKey,
            sessionKey: nil
        )
        if let sessionID = self.sessionID {
            let faceLivenessSwiftUIView = FaceLivenessDetectorView(
                sessionID: sessionID,
                credentialsProvider: customCredentialsProvider,
                region: "eu-west-1",
                disableStartView: false, // Your configuration
                isPresented: .constant(true),
                onCompletion: { result in
                    switch result {
                    case .success:
                        print("Liveness successfully completed")
                    case .failure(let error):
                        print("Liveness error: \(error)")
                    }
                }
            )
            
            let hostingController = createHostingController(with: faceLivenessSwiftUIView)
            addHostingControllerAsChild(hostingController)
            configureConstraints(for: hostingController.view)
        }
    }
``` 

### Console log output

```

(lldb) frame variable message
(AWSPredictionsPlugin.EventStream.Message) message = {
  totalByteLength = 189
  headersByteLength = 105
  preludeCRC = -1189361104
  headers = 3 values {
    [0] = {
      nameByteLength = 15
      name = ":exception-type"
      valueType = string
      valueByteLength = 27
      value = "UnrecognizedClientException"
    }
    [1] = {
      nameByteLength = 13
      name = ":content-type"
      valueType = string
      valueByteLength = 16
      value = "application/json"
    }
    [2] = {
      nameByteLength = 13
      name = ":message-type"
      valueType = string
      valueByteLength = 9
      value = "exception"
    }
  }
  payload = 68 bytes
  messageCRC = 1819087541
}
``` 

### Additional information and screenshots

![Uploading IMG_9950.png…]()
![Uploading IMG_9949.png…]()

**Comment by user2634** [comment]
Hi @ioanabrooks thanks, waiting for some updates

**Comment by phantumcode** [comment]
@user2634 Thanks for submitting the issue, we'll investigate and see if we can reproduce the issue.

**Comment by user2634** [comment]
thanks for answer I suppose the problem is in CredentialProvider this is the way how i create my custom provider. 
Can someone suggest how to do it correctly? 
I've also noticed that even when I pass empty values to accessKeyId = "" and let secretAccessKey = "" , the application's output doesn't change. The issue is most likely related to this.
```
struct MyCredentialsProvider: AWSCredentialsProvider {
    func fetchAWSCredentials() async throws -> AWSCredentials {
        let accessKeyId = Constants.accessKeyId
        let secretAccessKey = Constants.accessSecretKey

        let credentials = PBAWSCredentials(accessKeyId: accessKeyId, secretAccessKey: secretAccessKey)
        return credentials
    }
}

struct MyCredentialsProvider: AWSCredentials {
    let accessKeyId: String
    let secretAccessKey: String
} 
```

**Comment by phantumcode** [comment]
I've attached the [sample app](https://github.com/aws-amplify/amplify-ui-swift-liveness/files/12770995/SampleApp.zip) I used for testing.

The sample app uses [Amplify Auth to authenticate](https://docs.amplify.aws/lib/auth/signin/q/platform/ios/) and [Amplify API](https://docs.amplify.aws/lib/restapi/fetch/q/platform/ios/) to execute the REST API to get the session id.  By default, Liveness will look for the AWS Credentials from Amplify Auth if there is no credential providers ([as seen in code here](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/LivenessCredentials.swift#L18-L26)).

If your AWSCredentials are temporary has an associated session token and expiration, you'll need to conform to the protocol `AWSTemporaryCredentials`.  For example:
```
public struct MyAWSCredentials: AWSTemporaryCredentials {
    public let sessionToken: String
    public let expiration: Date
    public let accessKeyId: String
    public let secretAccessKey: String
}
```

**Comment by phantumcode** [comment]
@user2634 Were you unable to resolve your issue?

**Comment by user2634** [comment]
Hi @phantumcode  unfortunately, it still doesn't work with custom credential provider. I've debugged everything, is set up correctly [here](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/LivenessCredentials.swift#L17C1-L17C1), but for some reason, it's not working.

I've tried all the suggestions from the comments above, and I see a screen with the camera and i see a prompt "Move face in front of the camera" But after that, nothing happens, and I immediately get this error. The face capture oval is not displayed, and the scanning itself does not start. 



Error
```
FaceLivenessDetector[60056:5236099] Connection 2: received failure notification
Liveness error: FaceLivenessDetectionError(code: 0, message: "An unknown error occurred.", recoverySuggestion: "Please open an issue....") 
```

**Comment by phantumcode** [comment]
@user2634 A couple of suggestions/questions
* When you see the prompt "Move face in front of the camera", are you moving your face in the camera view and holding it there for a few seconds; if the oval doesn't appear, are you trying to move your face to different distances (closer or farther away)?  
* Does it still fail if you update the custom credential provider with the `sessionToken` and `expiration`?
* Does the same custom credential provider work on Android?
* Is it possible to verify or test the backend to support unauthenticated/guest user?

**Comment by user2634** [comment]
hi @phantumcode  
1) Sure, I've tried different things. When I see the "Move face in front of the camera" prompt, I put my face in the camera view and hold it there for a few seconds. If the oval doesn't appear, I also try moving my face closer or farther away from the camera. But no matter what I do, the error comes back right away as soon as my face shows up on the screen.

2) Yeah, it still fails with the updated custom credential provider with the `sessionToken` and `expiration` using credentials that confirm this `AWSTemporaryCredentialsProtocol`.

3) yes the same approach with custom credential provider and the same backend works fine for android here code example(Android)
```
FaceLivenessDetectorView

                FaceLivenessDetector(
                    sessionId = viewModel.data?.sessionId.orEmpty(),
                    region = "eu-west-1",
                    credentialsProvider = viewModel.credentialsProvider,
                    disableStartView = true,
                    onComplete = viewModel::onComplete,
                    onError = viewModel::onError
                    

ViewModel 
    val credentialsProvider = object : AWSCredentialsProvider<AWSCredentials> {
        override fun fetchAWSCredentials(
            onSuccess: Consumer<AWSCredentials>,
            onError: Consumer<AuthException>
        ) {
            onSuccess.accept(AWSCredentials(accessKeyId, accessSecretKey)) //git ignored keys
        }
    }
```
4) Im not sure about it, I dont have access to backend, but I can double check it with backend side

**Comment by phantumcode** [comment]
@user2634 Can you also provide 2-3 sample session ids and timestamps that are failing?

**Comment by phantumcode** [comment]
@user2634 Any additional updates or can you provide 2-3 sample session ids that has the failure to help troubleshoot?

**Comment by user2634** [comment]
@phantumcode already fixed, somehow i suppose it was backend issue or some problems with network. Thanks a lot for help and support
