### ISSUE TITLE
Xcode 15's Localizable.xcstrings file doesn't override Localizable.strings file from Host.app

### ISSUE THREAD

**Issue by haarj** [aws-amplify/amplify-ui-swift-liveness#53]
I added all of the keys from the Host.app's Localizable.strings file inside my app's Xcode 15 Localizable.xcstrings file but the bundle selected in the "resource_bundle_accessor.swift" file is always selecting the "AmplifyUILiveness_FaceLiveness" module name.

**Comment by haarj** [comment]
Thanks, @phantumcode! Much appreciated. :)

**Comment by phantumcode** [comment]
@haarj Unfortunately, the library currently does not support pulling in strings file at the app level.  You'll need to pull the library down locally and update the localization files defined in the library by adding the language you want to support (i.e. add a new `<language>.lproj` and `Localizable.strings` file under [Resources](https://github.com/aws-amplify/amplify-ui-swift-liveness/tree/main/Sources/FaceLiveness/Resources) folder in the library).

**Comment by haarj** [comment]
It is possible to include this functionality in the Swift package? Is it in the roadmap?Thanks!On Oct 2, 2023, at 2:44 PM, Tuan Pham ***@***.***> wrote:﻿
@haarj Unfortunately, the library currently does not support pulling in strings file at the app level.  You'll need to pull the library down locally and update the localization files defined in the library by adding the language you want to support (i.e. add a new <language>.lproj and Localizable.strings file under Resources folder in the library).

**Comment by phantumcode** [comment]
@haarj I've merged the PR to add support for localization files defined in the app's main bundle.  It will be included in the next release of the library.

**Comment by phantumcode** [comment]
Released in version [1.1.2](https://github.com/aws-amplify/amplify-ui-swift-liveness/releases/tag/1.1.2)
