### ISSUE TITLE
App rejected for use of NSSpeechRecognitionUsageDescription

### ISSUE THREAD

**Issue by ntnmrndn** [aws-amplify/amplify-ui-swift-liveness#67]
Hello, 

Since we started using face liveness, our builds are rejected due to not including the `NSSpeechRecognitionUsageDescription` string. 

It looks like Amplify Liveness has a dependency on Amplify which in turns, uses the Speech library ( Amplify => AmplifyPlugins > CoreMLPredictionsPlugin )
Is there a way to better restrict which part of your libraries are included so that we don't need to add an unnecessary permission ?

**Comment by phantumcode** [comment]
@ntnmrndn Thanks for submitting your question.  Unfortunately, that is a dependency that we can't remove and the current workaround is to add the usage description.  Alternatively, you could fork Amplify Swift and remove CoreMLPredictionsPlugin if that simplifies your development.

**Comment by phantumcode** [comment]
Closing issue, please re-open if there are any additional issues or questions.
