### ISSUE TITLE
App crashed when starting face liveness check

### ISSUE THREAD

**Issue by wind15973** [aws-amplify/amplify-ui-swift-liveness#69]
Hello
We built an app with Amplify 2.18.0 and AmplifyUILiveness 1.1.1.
We encountered a crash that happened frequently on iOS 17.
crash report from Xcode:
<img width="768" alt="截圖 2023-10-30 下午6 07 50" src="https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/4263011/3e24c3e4-5296-4bd5-9e26-8e5e8848675b">
crash report from Firebase:
<img width="1167" alt="截圖 2023-10-30 下午6 10 40" src="https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/4263011/1b3fe897-c409-4f14-a25f-0a85bbeb2400">

**Comment by phantumcode** [comment]
@wind15973 Can you confirm that liveness works in other scenario (e.g. on iOS 15 or 16)?  Do you have a working backend configured?

**Comment by wind15973** [comment]
Liveness works on iOS 15 and above.
This crash happened 99% on iOS 17 and 1% on other OS versions.
It happened intermittently and there were no specific steps to reproduce it.

**Comment by phantumcode** [comment]
@wind15973 Is it possible for you to provide the iOS crash log?  What is the crash rate per session?  Is the crash occurring in a specific client region or backend region?

**Comment by phantumcode** [comment]
@wind15973 We have not been able to reproduce this crash, so any additional details to help understand the crash would be much appreciated.

**Comment by phantumcode** [comment]
Please verify if this is still an issue in the latest release [v1.2.1](https://github.com/aws-amplify/amplify-ui-swift-liveness/releases/tag/1.2.1)

**Comment by wind15973** [comment]
This crash is fixed after upgrading to the latest release v1.2.1
Thanks for help
