### ISSUE TITLE
Not able to add this library to podspecs

### ISSUE THREAD

**Issue by zaherhadiar** [aws-amplify/amplify-ui-swift-liveness#72]
I am adding this spm to my cocoapods project.
https://github.com/aws-amplify/amplify-ui-swift-liveness
I am not able to add it also to podspec.Since when i installed the podfile in my project it is giving an error on Faceliveness not found

**Comment by zaherhadiar** [comment]
if we have a podfile for **Faceliveness** it will be good

**Comment by finexusCriss** [comment]
I'm also actively finding a solution to this, hopefully there is a solution to making this library available into my own React Native SDK

**Comment by phantumcode** [comment]
@zaherhadiar Unfortunately, we currently only support the library via SPM.  There is currently no plan to support Cocoapod.

**Comment by zaherhadiar** [comment]
I already have a CocoaPods SDK, and I injected an SPM library as well. Then, I installed my pod into my project, but it did not work, as it is giving me a 'FaceLiveness not found' error.
 Any suggested solution ?

**Comment by phantumcode** [comment]
Can you share how you're creating your pod and how you're integrating that into your project?

**Comment by zaherhadiar** [comment]
I already have a pod spec, i added SPM to the framework then I created the swift ui class and build the SDK.
I my podpsec i added

```
s.spm_dependency(
     url: 'https://github.com/aws-amplify/amplify-ui-swift-liveness.git',
     requirement: {kind: 'upToNextMajorVersion', minimumVersion: '1.1.4'},
     products: ['Amplify', 'FaceLiveness']
   )
```

I my project I added 
require_relative './spm_dependencies_poc.rb'
to my pod file inaddition to my pod.
After pod install the is automatically installed in my project but after build it is giving me duplicate symbols

**Comment by zaherhadiar** [comment]
@phantumcode any feedback?

**Comment by phantumcode** [comment]
@zaherhadiar The Liveness library has a dependency on the Amplify library via SPM, how is that being resolve? Similiarly, Amplify has external dependencies to other libraries i.e. StarScream and AWS Swift SDK.

**Comment by phantumcode** [comment]
Closing issue due inactivity.
