### ISSUE TITLE
No translation for LivenessStateMachine.FaceNotPreparedReason

### ISSUE THREAD

**Issue by ntnmrndn** [aws-amplify/amplify-ui-swift-liveness#76]
No translation is performed for `LivenessStateMachine.FaceNotPreparedReason` and it will be displayed as is in English

**Comment by phantumcode** [comment]
@ntnmrndn Thanks for submitting the issue.  We'll investigate further and provide a fix shortly.

**Comment by phantumcode** [comment]
Fix will be merge and release as part of next library release.

**Comment by phantumcode** [comment]
Fixed available in latest release.
