### ISSUE TITLE
Crash with NSInternalInconsistencyException 

### ISSUE THREAD

**Issue by ntnmrndn** [aws-amplify/amplify-ui-swift-liveness#81]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) before appending pixel buffers'

This happened when retrying again after a a liveness verification froze before timing out. 

Might be related: https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/74#issue-1990100117

**Comment by phantumcode** [comment]
@ntnmrndn Thanks for submitting the issue, we'll investigate and provide a fix soon.

**Comment by phantumcode** [comment]
Closing this as a duplicate of #68
