### ISSUE TITLE
Does this support Swift macos app development?

### ISSUE THREAD

**Issue by sumitaka-ueda-rv** [aws-amplify/amplify-ui-swift-liveness#90]
I installed the package to develop a macos app, but I get an error when building.
I figured this was due to not being compatible with macos.

**Error Description**
The package product 'AWSPluginsCore' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.13
The package product 'AWSCognitoAuthPlugin' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.13
The package product 'AWSPredictionsPlugin' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.13

**Environment**
Xcode version: 14.3.1
Amplify version: 2.23.0
AmplifyUILiveness version: 1.2.1
swift-driver version: 1.75.2 Apple Swift version 5.8.1 
Target: arm64-apple-macosx13.0

**Comment by ntnmrndn** [comment]
The issue is on your side, we use swift macro without any issue.

**Comment by phantumcode** [comment]
@ntnmrndn MacOS is currently not supported.

**Comment by ntnmrndn** [comment]
Somehow I don't know how to read and don't know the difference between macOS and macros anymore.
I've had luck with making a Catalina app for macOS with amplify.

**Comment by talksik** [comment]
oof, that's a bummer. any ideas when this will be supported on macOS? Also, is there a plan to isolate this from AWS Amplify? There seems to be a lot of bloat for people who just want to use Rekognition.

**Comment by talksik** [comment]
Any update @phantumcode ? Thanks 🙏🏽
