### ISSUE TITLE
Liveness without Cognito

### ISSUE THREAD

**Issue by komus** [aws-amplify/amplify-ui-swift-liveness#95]
I am trying to use liveness accesskey and secretkey, but getting the below error

_Liveness error: FaceLivenessDetectionError(code: 4, message: "Not authorized to perform a face liveness check.", recoverySuggestion: "Valid credentials are required for the face liveness check.")_

The service account is assigned permission policy `AdministratorAccess-Amplify`, can you assist with what is wrong
`
       let accessKey = ""
        let secretKey = ""
        let credentialsProvider = myCredentialProvider {
            myAWSCredentials(accessKeyId: accessKey, secretAccessKey: secretKey)
        }
        self.sessionID = ""
        
        if let sessionID = self.sessionID {
            let faceLivenessSwiftUIView = FaceLivenessDetectorView(
                sessionID: sessionID,
                credentialsProvider: credentialsProvider,
                region: "us-east-1",
                disableStartView: false,
                isPresented: .constant(true),
                onCompletion: { result in
                    switch result {
                    case .success:
                        print("Liveness successfully completed")
                    case .failure(let error):
                        print("Liveness error: \(error)")
                    }
                }
            )
            
            let hostingController = createHostingController(with: faceLivenessSwiftUIView)
            addHostingControllerAsChild(hostingController)
            configureConstraints(for: hostingController.view) `

**Comment by phantumcode** [comment]
@komus Can you verify that your IAM policies are configured appropriately and ensure the region is correct.

The role associate with the credential should have permission to start face liveness
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "rekognition:StartFaceLivenessSession",
            "Resource": "*"
        }
    ]
}
```

Your backend service/lambda should have permission to create the session id and get the liveness result
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "rekognition:CreateFaceLivenessSession"
            ],
            "Resource": "*"
        }
    ]
}

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "rekognition:GetFaceLivenessSessionResults",
            "Resource": "*"
        }
    ]
}
```

**Comment by komus** [comment]
Thank you @phantumcode, the permission was missing from the default AWS amplify permission. The suggestion worked
