### ISSUE TITLE
Camera still runs in background 

### ISSUE THREAD

**Issue by blacktorch** [aws-amplify/amplify-ui-swift-liveness#98]
Camera still runs is background even after the liveness session is completed.

**Comment by phantumcode** [comment]
@blacktorch Thanks for submitting your issue.  Can you provide detailed steps to help us investigate and reproduce the issue?

**Comment by blacktorch** [comment]
Steps to reproduce:
- Start liveness check
- Once liveness check is completed, you can still tell that the camera is still running in the background because the green dot at the top of the screen is still on.
I have only observed this is version 1.2.2 but does not occur in version 1.1.1, so all I had to do was roll back.

You can test this with the host app.
