### ISSUE TITLE
 AVAsset Crash [AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 2'

### ISSUE THREAD

**Issue by MRJYL** [aws-amplify/amplify-ui-swift-liveness#99]
erminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 2

**Comment by phantumcode** [comment]
@MRJYL Thanks for submitting your issue.  Can you provide detail steps to help us investigate and reproduce the issue?  Additionally, what iOS version and device are you seeing this issue in? Is this a native iOS app or a ReactNative or Flutter app?  Is it possible for you to provide a sample app?

**Comment by MRJYL** [comment]
We notice that the "finishWritingWithCompletionHandle"r was called twice in a short time

**Comment by phantumcode** [comment]
@MRJYL Can you provide detailed steps to reproduce? Is this occurring on all iOS versions or devices? Is it possible for you to provide a sample app?

**Comment by phantumcode** [comment]
Issue fixed in [v1.2.5](https://github.com/aws-amplify/amplify-ui-swift-liveness/releases/tag/1.2.5)

**Comment by MRJYL** [comment]
I'm not sure this fix will work,  the value of state always be . awaitingSingleFrame.
![image](https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/12264960/7b87cd1e-af37-41c6-8180-76f86de6ad4b)

**Comment by MRJYL** [comment]
Maybe `if assetWriter.status != .completed {...}` shoud be used here, I notice the state always be .awaitingSingleFrame here, It doesn't work as expected. @phantumcode
